"""

Revision ID: 0d0f35cad0c5
Revises: b1880af5873d
Create Date: 2026-02-04 14:59:04.373264

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d0f35cad0c5'
down_revision = 'b1880af5873d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artisan', 'last_name')
    op.drop_column('artisan', 'phone')
    op.drop_column('artisan', 'first_name')
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'first_name')
    op.add_column('user_account', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user_account', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user_account', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'phone')
    op.drop_column('user_account', 'last_name')
    op.drop_column('user_account', 'first_name')
    op.add_column('customer', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
