"""

Revision ID: 24411367cd8c
Revises: 
Create Date: 2026-03-13 13:37:52.160236

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24411367cd8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_is_active'), 'user_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_account_is_admin'), 'user_account', ['is_admin'], unique=False)
    op.create_index(op.f('ix_user_account_last_login_at'), 'user_account', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_user_account_uuid'), 'user_account', ['uuid'], unique=True)
    op.create_table('artisan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_company_name'), 'artisan', ['company_name'], unique=False)
    op.create_index(op.f('ix_artisan_user_id'), 'artisan', ['user_id'], unique=True)
    op.create_index(op.f('ix_artisan_uuid'), 'artisan', ['uuid'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_user_id'), 'customer', ['user_id'], unique=True)
    op.create_index(op.f('ix_customer_uuid'), 'customer', ['uuid'], unique=True)
    op.create_table('artisan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DECLINED', 'ACCEPTED', 'COMPLETED', 'New', 'Revision', name='jobstatus'), nullable=False),
    sa.Column('negotiated_amount', sa.BigInteger(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completion_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('revision_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acceptedat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_uuid', sa.Uuid(), nullable=False),
    sa.Column('artisan_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_uuid'], ['artisan.uuid'], ),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_jobs_artisan_uuid'), 'artisan_jobs', ['artisan_uuid'], unique=False)
    op.create_index(op.f('ix_artisan_jobs_customer_uuid'), 'artisan_jobs', ['customer_uuid'], unique=False)
    op.create_index(op.f('ix_artisan_jobs_status'), 'artisan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_artisan_jobs_uuid'), 'artisan_jobs', ['uuid'], unique=True)
    op.create_table('artisan_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sa.Enum('ProjectUpdateReminder', 'ClietFeedback', 'NewProjectAlert', name='artisannotificationtopic'), nullable=False),
    sa.Column('artisan_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_uuid'], ['artisan.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_notification_artisan_uuid'), 'artisan_notification', ['artisan_uuid'], unique=False)
    op.create_index(op.f('ix_artisan_notification_uuid'), 'artisan_notification', ['uuid'], unique=True)
    op.create_table('artisan_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('customer_uuid', sa.Uuid(), nullable=False),
    sa.Column('artisan_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_uuid'], ['artisan.uuid'], ),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_review_artisan_uuid'), 'artisan_review', ['artisan_uuid'], unique=False)
    op.create_index(op.f('ix_artisan_review_customer_uuid'), 'artisan_review', ['customer_uuid'], unique=False)
    op.create_index(op.f('ix_artisan_review_uuid'), 'artisan_review', ['uuid'], unique=True)
    op.create_table('artisan_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('artisan_uuid', sa.Uuid(), nullable=False),
    sa.Column('total_balance', sa.BigInteger(), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_uuid'], ['artisan.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_wallet_artisan_uuid'), 'artisan_wallet', ['artisan_uuid'], unique=True)
    op.create_index(op.f('ix_artisan_wallet_uuid'), 'artisan_wallet', ['uuid'], unique=True)
    op.create_table('customer_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_uuid', sa.Uuid(), nullable=False),
    sa.Column('total_balance', sa.BigInteger(), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_wallet_customer_uuid'), 'customer_wallet', ['customer_uuid'], unique=True)
    op.create_index(op.f('ix_customer_wallet_uuid'), 'customer_wallet', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_wallet_uuid'), table_name='customer_wallet')
    op.drop_index(op.f('ix_customer_wallet_customer_uuid'), table_name='customer_wallet')
    op.drop_table('customer_wallet')
    op.drop_index(op.f('ix_artisan_wallet_uuid'), table_name='artisan_wallet')
    op.drop_index(op.f('ix_artisan_wallet_artisan_uuid'), table_name='artisan_wallet')
    op.drop_table('artisan_wallet')
    op.drop_index(op.f('ix_artisan_review_uuid'), table_name='artisan_review')
    op.drop_index(op.f('ix_artisan_review_customer_uuid'), table_name='artisan_review')
    op.drop_index(op.f('ix_artisan_review_artisan_uuid'), table_name='artisan_review')
    op.drop_table('artisan_review')
    op.drop_index(op.f('ix_artisan_notification_uuid'), table_name='artisan_notification')
    op.drop_index(op.f('ix_artisan_notification_artisan_uuid'), table_name='artisan_notification')
    op.drop_table('artisan_notification')
    op.drop_index(op.f('ix_artisan_jobs_uuid'), table_name='artisan_jobs')
    op.drop_index(op.f('ix_artisan_jobs_status'), table_name='artisan_jobs')
    op.drop_index(op.f('ix_artisan_jobs_customer_uuid'), table_name='artisan_jobs')
    op.drop_index(op.f('ix_artisan_jobs_artisan_uuid'), table_name='artisan_jobs')
    op.drop_table('artisan_jobs')
    op.drop_index(op.f('ix_customer_uuid'), table_name='customer')
    op.drop_index(op.f('ix_customer_user_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_artisan_uuid'), table_name='artisan')
    op.drop_index(op.f('ix_artisan_user_id'), table_name='artisan')
    op.drop_index(op.f('ix_artisan_company_name'), table_name='artisan')
    op.drop_table('artisan')
    op.drop_index(op.f('ix_user_account_uuid'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_last_login_at'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_admin'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_active'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
