"""initial migration

Revision ID: 4e2dcc7dac22
Revises:
Create Date: 2025-09-21 18:57:08.030493

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4e2dcc7dac22"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_account_email"), "user_account", ["email"], unique=True)
    op.create_index(op.f("ix_user_account_is_active"), "user_account", ["is_active"], unique=False)
    op.create_index(op.f("ix_user_account_is_admin"), "user_account", ["is_admin"], unique=False)
    op.create_index(
        op.f("ix_user_account_last_login_at"), "user_account", ["last_login_at"], unique=False
    )
    op.create_index(op.f("ix_user_account_uuid"), "user_account", ["uuid"], unique=False)
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_company_name"), "client", ["company_name"], unique=False)
    op.create_index(op.f("ix_client_contact_email"), "client", ["contact_email"], unique=False)
    op.create_index(op.f("ix_client_user_id"), "client", ["user_id"], unique=True)
    op.create_index(op.f("ix_client_uuid"), "client", ["uuid"], unique=False)
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_user_id"), "customer", ["user_id"], unique=True)
    op.create_index(op.f("ix_customer_uuid"), "customer", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_uuid"), table_name="customer")
    op.drop_index(op.f("ix_customer_user_id"), table_name="customer")
    op.drop_table("customer")
    op.drop_index(op.f("ix_client_uuid"), table_name="client")
    op.drop_index(op.f("ix_client_user_id"), table_name="client")
    op.drop_index(op.f("ix_client_contact_email"), table_name="client")
    op.drop_index(op.f("ix_client_company_name"), table_name="client")
    op.drop_table("client")
    op.drop_index(op.f("ix_user_account_uuid"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_last_login_at"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_is_admin"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_is_active"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_table("user_account")
    # ### end Alembic commands ###
