"""

Revision ID: 99a7e87d44fb
Revises: 0d0f35cad0c5
Create Date: 2026-02-04 15:05:11.131488

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '99a7e87d44fb'
down_revision = '0d0f35cad0c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
