"""

Revision ID: a6e662063d90
Revises: ba55bbba0369
Create Date: 2026-03-05 09:04:08.481356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a6e662063d90'
down_revision = 'ba55bbba0369'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artisan_uuid'), table_name='artisan')
    op.create_index(op.f('ix_artisan_uuid'), 'artisan', ['uuid'], unique=True)
    op.drop_index(op.f('ix_customer_uuid'), table_name='customer')
    op.create_index(op.f('ix_customer_uuid'), 'customer', ['uuid'], unique=True)

    op.create_table('artisan_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('artisan_uuid', sa.Uuid(), nullable=False),
    sa.Column('total_balance', sa.BigInteger(), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artisan_uuid'], ['artisan.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_wallet_artisan_uuid'), 'artisan_wallet', ['artisan_uuid'], unique=True)
    op.create_index(op.f('ix_artisan_wallet_uuid'), 'artisan_wallet', ['uuid'], unique=True)
    op.create_table('customer_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_uuid', sa.Uuid(), nullable=False),
    sa.Column('total_balance', sa.BigInteger(), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('debited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_wallet_customer_uuid'), 'customer_wallet', ['customer_uuid'], unique=True)
    op.create_index(op.f('ix_customer_wallet_uuid'), 'customer_wallet', ['uuid'], unique=True)
    op.add_column('user_account', sa.Column('profile_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_account', sa.Column('bank_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_user_account_uuid'), table_name='user_account')
    op.create_index(op.f('ix_user_account_uuid'), 'user_account', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_uuid'), table_name='user_account')
    op.create_index(op.f('ix_user_account_uuid'), 'user_account', ['uuid'], unique=False)
    op.drop_column('user_account', 'bank_account_name')
    op.drop_column('user_account', 'bank_account_number')
    op.drop_column('user_account', 'bank_name')
    op.drop_column('user_account', 'profession')
    op.drop_column('user_account', 'state')
    op.drop_column('user_account', 'city')
    op.drop_column('user_account', 'postal_code')
    op.drop_column('user_account', 'street_address')
    op.drop_column('user_account', 'date_of_birth')
    op.drop_column('user_account', 'profile_photo')
    op.drop_index(op.f('ix_customer_uuid'), table_name='customer')
    op.create_index(op.f('ix_customer_uuid'), 'customer', ['uuid'], unique=False)
    op.drop_index(op.f('ix_artisan_uuid'), table_name='artisan')
    op.create_index(op.f('ix_artisan_uuid'), 'artisan', ['uuid'], unique=False)
    op.drop_index(op.f('ix_customer_wallet_uuid'), table_name='customer_wallet')
    op.drop_index(op.f('ix_customer_wallet_customer_uuid'), table_name='customer_wallet')
    op.drop_table('customer_wallet')
    op.drop_index(op.f('ix_artisan_wallet_uuid'), table_name='artisan_wallet')
    op.drop_index(op.f('ix_artisan_wallet_artisan_uuid'), table_name='artisan_wallet')
    op.drop_table('artisan_wallet')
    # ### end Alembic commands ###
