"""

Revision ID: ba55bbba0369
Revises: 
Create Date: 2026-02-17 16:06:49.875497

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba55bbba0369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_is_active'), 'user_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_account_is_admin'), 'user_account', ['is_admin'], unique=False)
    op.create_index(op.f('ix_user_account_last_login_at'), 'user_account', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_user_account_uuid'), 'user_account', ['uuid'], unique=False)
    op.create_table('artisan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artisan_company_name'), 'artisan', ['company_name'], unique=False)
    op.create_index(op.f('ix_artisan_user_id'), 'artisan', ['user_id'], unique=True)
    op.create_index(op.f('ix_artisan_uuid'), 'artisan', ['uuid'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_user_id'), 'customer', ['user_id'], unique=True)
    op.create_index(op.f('ix_customer_uuid'), 'customer', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_uuid'), table_name='customer')
    op.drop_index(op.f('ix_customer_user_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_artisan_uuid'), table_name='artisan')
    op.drop_index(op.f('ix_artisan_user_id'), table_name='artisan')
    op.drop_index(op.f('ix_artisan_company_name'), table_name='artisan')
    op.drop_table('artisan')
    op.drop_index(op.f('ix_user_account_uuid'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_last_login_at'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_admin'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_active'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
