"""

Revision ID: ca51eeaeb5d8
Revises: a6e662063d90
Create Date: 2026-03-10 22:17:38.512311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca51eeaeb5d8'
down_revision = 'a6e662063d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for col in (
        "profile_photo",
        "date_of_birth",
        "street_address",
        "postal_code",
        "city",
        "state",
        "profession",
        "bank_name",
        "bank_account_number",
        "bank_account_name",
    ):
        op.execute(f"UPDATE user_account SET {col} = '' WHERE {col} IS NULL")

    op.alter_column('user_account', 'profile_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'profession',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'bank_account_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_account', 'bank_account_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'bank_account_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'bank_account_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'profession',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_account', 'profile_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
